version: "3"

networks:
    elk-filebeat:
        external: true

services:
    elasticsearch:
        image: elasticsearch
        container_name: elasticsearch
        hostname: elasticsearch
        restart: always
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch/:/usr/share/elasticsearch/data
            - ./logs/elasticsearch/:/var/log/elasticsearch
        networks:
            - elk-filebeat
            
    kibana:
        image: kibana
        container_name: kibana
        hostname: kibana
        restart: always
        volumes:
            - ./logs/kibana/:/var/log/kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elk-filebeat
            
    logstash:
        image: logstash
        container_name: logstash
        hostname: logstash
        ports:
            - "5044:5044"
        volumes:
            - ./logstash/config:/config-dir
            - ./logs/logstash/:/var/log/logstash
        depends_on:
            - elasticsearch
        command: logstash -f /config-dir
        networks:
            - elk-filebeat
        external_links:
            - nginx:nginx
