version: "3"

networks:
    elk:

services:
    elasticsearch:
        image: elasticsearch
        container_name: elasticsearch
        hostname: elasticsearch
        restart: always
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch/:/usr/share/elasticsearch/data
            - ./logs/elasticsearch/:/var/log/elasticsearch
        networks:
            - elk
            
    kibana:
        image: kibana
        container_name: kibana
        hostname: kibana
        restart: always
        volumes:
            - ./logs/kibana/:/var/log/kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elk
            
    logstash:
        image: logstash
        container_name: logstash
        hostname: logstash
        ports:
            - "5044:5044"
        volumes:
            - ./logstash/config:/config-dir
            - ./logs/logstash/:/var/log/logstash
        depends_on:
            - elasticsearch
        command: logstash -f /config-dir
        networks:
            - elk
        extra_hosts:
            - "api.ucie.local:172.22.0.1"
            